name: PressF
version: ${project.version}
main: me.ryzenfromfire.pressf.PressF
api-version: 1.16
authors: [ RyzenFromFire ]
description: PressF is a Minecraft plugin that allows users to press F to pay respects.
commands:
  pressf:
    description: Press F to pay respects.
    usage: /pressf <target> <show_global_message>
    aliases: pf
  viewf:
    description: See how many Fs you have been given.
    usage: /viewf
    aliases: viewfs
  pressftop:
    description: A leaderboard of who has accumulated the most Fs.
    usage: /pftop
    aliases: [pftop, pfleaderboard, pflb, pressflb]
  pfadmin:
    description: Handles admin commands, like reloading the config.
    usage: /pfadmin <reload | load | save>
    permission: pressf.admin
